new Equation added QTechCost which computes technology cost
giannou/OPEN-PROM pull request #12
Opened 2023-04-26 14:10 UTC by riazis

2023-04-27 09:06 UTC, giannou requested changes

2023-04-27 09:06 UTC, giannou commented on input.gms
> +table iElaSub(allCy,DSBS)                           "Elasticities by subsectors"
units?

2023-04-27 09:06 UTC, giannou commented on input.gms
> +table iConsSizeDistHeat(allCy,conSet)                "Consumer sizes for district heating"
units?

2023-04-27 09:06 UTC, giannou commented on input.gms
> +iAnnConsModCons(runCy,"BU") = 0.5 ;
this whole section (lines 92-158) needs to be reworked. to proceed, let's keep as it is for now and I will open an issue (assigning myself) to work on this

2023-05-03 12:50 UTC, riazis commented on preloop.gms
> +iNcon(SBS) =1;
It was a test. Resolved now

2023-05-03 12:50 UTC, riazis commented on input.gms
> +table iElaSub(allCy,DSBS)                           "Elasticities by subsectors"
Solved

2023-05-03 12:51 UTC, riazis commented on input.gms
> +table iConsSizeDistHeat(allCy,conSet)                "Consumer sizes for district heating"
Solved

2023-05-03 12:53 UTC, riazis commented on equations.gms
> +              (0$(not CHP(EF)) + (VFuelPriceSub(runCy,"OI","ELC",YTIME)*iFracElecPriChp(runCy,YTIME)*VElecIndPrices(runCy,YTIME))$CHP(EF)))) + SQR(1e-7) ) )/2;
Fixed

2023-05-03 14:40 UTC, giannou approved these changes
looks good to me, thanks

2023-05-03 14:42 UTC, merged