QElecProdCos added
giannou/OPEN-PROM pull request #9
Opened 2023-04-21 08:39 UTC by riazis

-new equation added

2023-04-21 08:58 UTC, giannou requested changes

2023-04-21 08:58 UTC, giannou commented on declarations.gms
> +iResDemSub(allCy,SBS,YTIME)                 "Residuals in total energy demand per subsector (energy intensity)"
"energy intensity" is not a unit

2023-04-21 08:58 UTC, giannou commented on equations.gms
> +                    )/(iAvailRateChp(runCy,CHP)*8.76)/1000
please define a scalar (or use an existing) for 8.76

2023-04-21 08:58 UTC, giannou commented on equations.gms
> +                      * iCapCosChp(runCy,CHP,YTIME)* 1E3 * iCGI(runCy,YTIME)  + iFixOandMCosChp(runCy,CHP,YTIME)
please change `1E3` to `1000`

2023-04-21 08:58 UTC, giannou commented on equations.gms
> +
please remove empty lines

2023-04-21 08:58 UTC, giannou commented on equations.gms
> +                         *0.086/(   iBoiEffChp(runCy,CHP,YTIME)*VElecIndPrices(runCy,YTIME)    )
is `0.086` the scalar `sTWhToMtoe` maybe?

2023-04-21 09:15 UTC, giannou commented on equations.gms
> +QElecProdCos(runCy,DSBS,CHP,YTIME)$(TIME(YTIME) $INDDOM(DSBS))..
An execution error (division by zero) happens somewhere in this equation.

2023-04-21 09:15 UTC, giannou requested changes

2023-04-21 09:15 UTC, giannou commented on equations.gms
> +QElecProdCos(runCy,DSBS,CHP,YTIME)$(TIME(YTIME) $INDDOM(DSBS))..
An execution error (division by zero) happens somewhere in this equation.

2023-04-24 10:49 UTC, riazis commented on declarations.gms
> +iResDemSub(allCy,SBS,YTIME)                 "Residuals in total energy demand per subsector (energy intensity)"
fixed

2023-04-24 10:58 UTC, riazis commented on equations.gms
> +                      * iCapCosChp(runCy,CHP,YTIME)* 1E3 * iCGI(runCy,YTIME)  + iFixOandMCosChp(runCy,CHP,YTIME)
fixed

2023-04-24 10:58 UTC, riazis commented on equations.gms
> +
fixed

2023-04-24 12:32 UTC, giannou commented on equations.gms
> +                    )/(iAvailRateChp(runCy,CHP)*8.76)/1000
fixed

2023-04-24 12:32 UTC, giannou commented on equations.gms
> +                         *0.086/(   iBoiEffChp(runCy,CHP,YTIME)*VElecIndPrices(runCy,YTIME)    )
fixed

2023-04-24 12:33 UTC, giannou commented on equations.gms
> +QElecProdCos(runCy,DSBS,CHP,YTIME)$(TIME(YTIME) $INDDOM(DSBS))..
fixed

2023-04-24 12:33 UTC, giannou approved these changes
great, thanks

2023-04-24 12:35 UTC, merged